### ISSUE TITLE
/bin/sh: dostextfile: No such file or directory

### ISSUE THREAD

**Issue by LTGZZ** [TexasInstruments/dri3wsegl#1]
Hi,

I followed the instructions, I'm in:
``~/ti-img-sgx/1.14.3699939/k4.14/eurasia_km/eurasiacon/build/linux2/omap5430_linux``

But I got:
``  CC [M]  /home/me/ti-img-sgx/1.14.3699939/k4.14/eurasia_km/eurasiacon/binary2_omap5430_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.o
/bin/sh: dostextfile: No such file or directory
make[3]: *** [scripts/Makefile.build:306: /home/me/ti-img-sgx/1.14.3699939/k4.14/eurasia_km/eurasiacon/binary2_omap5430_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.o] Error 1
rm /home/me/ti-img-sgx/1.14.3699939/k4.14/eurasia_km/eurasiacon/binary2_omap5430_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.c
make[2]: *** [Makefile:1515: _module_/home/me/ti-img-sgx/1.14.3699939/k4.14/eurasia_km/eurasiacon/binary2_omap5430_linux_release/target/kbuild] Error 2
make[1]: *** [eurasiacon/build/linux2/kbuild/kbuild.mk:56: kbuild] Error 2
make: *** [../config/core.mk:613: build] Error 2``

**Comment by tomba** [comment]
This project is dri3wsegl, not the sgx driver, so this is not the forum to discuss how to compile the sgx driver. But I don't think you followed the instructions in dri3wsegl's readme, as there isn't even a omap5430_linux directory in the branch, nor do the instructions mention such a directory.

**Comment by LTGZZ** [comment]
The instructions in the readme are the same than this github page.
I followed them, it failed.
For instance,
``cd $DDKROOT/eurasia_km/eurasiacon/build/linux2/omap_linux``
there is no omap_linux in any of the three git repos needed.
That's why I used the 5430 folder, as one exists.

Maybe you can explain me the procedure ?

**Comment by tomba** [comment]
There is omap_linux directory in the branch given in the instructions

**Comment by LTGZZ** [comment]
There's a mention about it in the instructions.
But when I clone the code, there's no such directory inside it.

**Comment by tomba** [comment]
You're not using the branch ti-img-sgx/1.14.3699939/k4.14 given in the instructions

**Comment by LTGZZ** [comment]
``$ ls ti-img-sgx/1.14.3699939/k4.14/eurasia_km/eurasiacon/build/linux2/``
``bits.mk       common/  kbuild/            moduledefs.mk    omap5430_linux/   tools/
buildvars.mk  config/  kernel_module.mk   modules.mk       prepare_tree.mk   toplevel.mk
commands.mk   defs.mk  kernel_version.mk  omap4430_linux/  this_makefile.mk``

**Comment by tomba** [comment]
You are not using the branch given in the instructions, but the master branch.

**Comment by LTGZZ** [comment]
There's only one branch here: the master.

**Comment by LTGZZ** [comment]
I checked every readme, nothing refers to another branch.
Can you point me to these "instructions" that you write about but never show please ?

**Comment by tomba** [comment]
The SGX kernel driver repository has many branches, and one of those is the one given in the instructions.

**Comment by LTGZZ** [comment]
Ok, where are those "instructions" so ?

**Comment by tomba** [comment]
With instructions I mean the README.md in dri3wsegl repository, master branch.

It gives, for the SGX kernel driver, both the git url and the branch: `git://git.ti.com/graphics/omap5-sgx-ddk-linux.git ti-img-sgx/1.14.3699939/k4.14`

**Comment by LTGZZ** [comment]
Yeah, I git cloned that URL.
There is no "omap_linux" directory in it.

**Comment by tomba** [comment]
Yes there is, in the correct branch, ti-img-sgx/1.14.3699939/k4.14

As mentioned in the Warning section, this is not a ready project with simple copy-pasteable instructions for building and using. No offense, but if you don't know how to get the correct git branch, I don't think you can get the rest working either.

Here's a command to clone the sgx kernel driver and checkout the correct branch:
`git clone -b ti-img-sgx/1.14.3699939/k4.14  git://git.ti.com/graphics/omap5-sgx-ddk-linux.git`

**Comment by LTGZZ** [comment]
Yeah I'm so dumb.
And you are soooo clever that you're not even able to write a proper documentation.

**Comment by tomba** [comment]
I believe the git url and the branch was given clearly, so I'm not sure how to improve that. If you are looking for commands to copy-paste, you won't find them here (please see the Warning section).
