### ISSUE TITLE
error: implicit declaration of function ‘init_timer’

### ISSUE THREAD

**Issue by LTGZZ** [TexasInstruments/dri3wsegl#2]
Hi,

while doing:
 ``~/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/build/linux2/omap_linux$ make -j4 $*``
I got:
`CC [M]  /home/me/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/binary2_omap_linux_release/target/kbuild/services4/srvkm/env/linux/proc.o
/home/me/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/binary2_omap_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.c: In function ‘OSAddTimer’:
/home/me/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/binary2_omap_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.c:2890:5: error: implicit declaration of function ‘init_timer’; did you mean ‘init_timers’? [-Werror=implicit-function-declaration]
     init_timer(&psTimerCBData->sTimer);
     ^~~~~~~~~~
     init_timers
/home/me/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/binary2_omap_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.c:2895:26: error: ‘struct timer_list’ has no member named ‘data’
     psTimerCBData->sTimer.data = (IMG_UINTPTR_T)psTimerCBData;
                          ^
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:305: /home/me/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/binary2_omap_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.o] Error 1
make[3]: *** Waiting for unfinished jobs....`

I'm using gcc-8.2.0 natively.

**Comment by tomba** [comment]
I don't know if the SGX kernel driver can be compiled natively. It's not exactly the cleanest piece of code. I have been using gcc-linaro-7.2.1-2017.11-x86_64_armv8l-linux-gnueabihf for cross compiling. Although the error looks more like it's related to the kernel version. That SGX driver version is made for kernel v4.14, and it likely has issues if the kernel version you have is (much) different from v4.14.

I should add a mention of the kernel versions, although those things are not exactly part of dri3wsegl.

But again, the SGX driver is a totally different project than this. I can't really give support on the SGX driver, unless it's directly related to dri3wsegl.

**Comment by LTGZZ** [comment]
It's on a 4.19-rc6.

**Comment by tomba** [comment]
I pushed a few additions to the README about the SGX, especially the kernel url + branch that I have been using. I hope it helps.
