### ISSUE TITLE
cast between incompatible function types

### ISSUE THREAD

**Issue by LTGZZ** [TexasInstruments/dri3wsegl#3]
Linux-4.14.74, gcc-8.2, native build:
`CC [M]  /home/def/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/binary2_omap_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.o
In file included from ./include/linux/workqueue.h:9,
                 from ./include/linux/srcu.h:34,
                 from ./include/linux/notifier.h:16,
                 from ./include/linux/memory_hotplug.h:7,
                 from ./include/linux/mmzone.h:781,
                 from ./include/linux/gfp.h:6,
                 from ./include/linux/mm.h:10,
                 from ./arch/arm/include/asm/cacheflush.h:13,
                 from /home/def/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/binary2_omap_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.c:55:
./include/linux/timer.h: In function ‘timer_setup’:
./include/linux/timer.h:179:23: error: cast between incompatible function types from ‘void (*)(struct timer_list *)’ to ‘void (*)(long unsigned int)’ [-Werror=cast-function-type]
  __setup_timer(timer, (TIMER_FUNC_TYPE)callback,
                       ^
./include/linux/timer.h:144:25: note: in definition of macro ‘__setup_timer’
   (_timer)->function = (_fn);    \
                         ^~~
/home/def/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/binary2_omap_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.c: In function ‘OSEventObjectCreateKM’:
/home/def/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/binary2_omap_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.c:3051:13: error: ‘strncpy’ specified bound 50 equals destination size [-Werror=stringop-truncation]
             strncpy(psEventObject->szName, pszName, EVENTOBJNAME_MAXLENGTH);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:329: /home/def/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/binary2_omap_linux_release/target/kbuild/services4/srvkm/env/linux/osfunc.o] Error 1
make[2]: *** [Makefile:1527: _module_/home/def/omap5-sgx-ddk-linux/eurasia_km/eurasiacon/binary2_omap_linux_release/target/kbuild] Error 2
make[1]: *** [eurasiacon/build/linux2/kbuild/kbuild.mk:56: kbuild] Error 2
make: *** [../config/core.mk:679: build] Error 2
`

**Comment by tomba** [comment]
Builds fine for me with v4.14.71, cross compiling with gcc-linaro-7.2.1-2017.11-x86_64_armv8l-linux-gnueabihf.

I'll close this as this issue is not about dri3wsegl.
